### ISSUE TITLE
Python voila will not start

### ISSUE THREAD

**Issue by j-simmons-phd** [Mach30/kasm-dof-workspace#22]
Will post error message later

**Comment by capsulecorplab** [comment]
![Screenshot from 2023-03-24 13-45-53](https://user-images.githubusercontent.com/14095576/227636129-4ecfa8ab-d41b-4134-b10f-206523fd7b2b.png)

**Comment by capsulecorplab** [comment]
```
$ voila
Traceback (most recent call last):
  File "/usr/local/bin/voila", line 5, in <module>
    from voila.app import main
  File "/usr/local/lib/python3.8/dist-packages/voila/app.py", line 40, in <module>
    from jupyter_server.services.kernels.handlers import KernelHandler, ZMQChannelsHandler
ImportError: cannot import name 'ZMQChannelsHandler' from 'jupyter_server.services.kernels.handlers' (/usr/local/lib/python3.8/dist-packages/jupyter_server/services/kernels/handlers.py)

```

**Comment by capsulecorplab** [comment]
try installing `ipywidgets`, `ipyvolume`, `bqplot`, and `scipy` as per https://voila.readthedocs.io/en/stable/using.html#the-example-notebooks

**Comment by capsulecorplab** [comment]
should also run `jupyter labextension install @jupyter-voila/jupyterlab-preview` as per https://www.kylabendt.com/blog/setting-up-jupyterlab-and-voila/

**Comment by capsulecorplab** [comment]
try (pip) installing `pyzmq` before voila and jupyter tools
