### ISSUE TITLE
link published package to release tags

### ISSUE THREAD

**Issue by capsulecorplab** [Mach30/kasm-dof-workspace#32]
releases should point to their associated package built and published to GHCR

- [x] tag name in image in `docker-compose.yml` should be semver tag
- [x] release notes should be automated from a `.github/release.yml`
- [ ] Docker meta in CI should include trigger for semver git tag (add tag, `type=ref,event=tag` as per https://github.com/docker/metadata-action#typeref)

## workflow

1. finish merging all PR's for upcoming release into `main`
2. update `docker-compose.yml` to point to upcoming release (i.e., semver tag)
3. create/push semver tag (subsequently triggering build from tags
4. wait for build from tag to complete
5. publish upcoming release

**Comment by j-simmons-phd** [comment]
Some research on managing releases. 

- https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#
