### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by capsulecorplab** [Mach30/kasm-dof-workspace#6]
The workspaces-core-images repo recently added a license and provided some guidance for licensing custom workspace images as per https://github.com/kasmtech/workspaces-core-images/issues/7#issuecomment-1201477990. Should probably do the same for the kasm-dof-workspace

**Comment by j-simmons-phd** [comment]
Resolved in https://github.com/Mach30/kasm-dof-workspace/commit/f9705395cf6a1a33bfc7b5762389681ef3e890c4
